#!/bin/bash

#Application/Module configuration
APP_NAME="vsc"
APP_VERSION="0.5 beta"
APP_TYPE="app"
APP_FUZZY_NAME="VScript Compiler"
#Past here... No touchy

appdata(){
  echo 'APP_NAME='"\"$APP_NAME\"" >> $1
  echo 'APP_FUZZY_NAME='"\"$APP_FUZZY_NAME\"" >> $1
  echo 'APP_VERSION='"\"$APP_VERSION\"" >> $1
  echo '' >> $1
  echo '#Pregenerated code ahead. Here be dragons?' >> $1
}


#Compiled in library
if [ "$APP_TYPE" == "lib" ]
then
  if [ "$1" == "-en" ]; then
     echo "enabled $APP_FUZZY_NAME" && touch ".en" && exit
  fi
  if [ "$1" == "-ds" ]; then
     echo "disable $APP_FUZZY_NAME" && rm -f ."en" && exit
  fi
  #clean out old blob
  rm -f $APP_NAME.vlib
  touch $APP_NAME.vlib

  #Compile classes
  for class in $(ls src); do
    cat src/$class >> $APP_NAME.vlib
    echo "Added class $class to library"
  done
  echo 'loadedLibs="$loadedLibs\n'"$APP_NAME V$APP_VERSION: $APP_FUZZY_NAME"'"' >> $APP_NAME.vlib
fi

if [ "$APP_TYPE" == "mod" ]
then

  rm -f $APP_NAME.vmod
  touch $APP_NAME.vmod

  for class in $(ls src); do
    cat src/$class >> $APP_NAME.vmod
    echo "Added class $class to module"
  done
  echo 'loadedMods="$loadedMods\n'"$APP_NAME V$APP_VERSION: $APP_FUZZY_NAME"'"' >> $APP_NAME.vmod
fi

if [ "$APP_TYPE" == "app" ]
then

  rm -f $APP_NAME
  touch "$APP_NAME"
  echo '#!/bin/bash' >> $APP_NAME
  echo "Created empty app bundle"



  appdata "$APP_NAME"
  echo "Added app data to bundle"

  if [ -e include/vsruntime.base ]
  then
    cat include/vsruntime.base >> $APP_NAME
  else
    rm -rf $APP_NAME
    echo "ERROR: Missing runtime."
    exit
  fi

if [ $(ls -1 *.vmod 2>/dev/null | wc -l) != 0 ]
then
    for mod in $(ls include/*.vmod)
    do
      cat $mod >> $APP_NAME
    done
fi
  if [ ! -e src/main.vss ]
  then
    echo "Main class not found, exiting"
    exit
  fi
  for class in $(ls src)
  do
    cat src/$class >> $APP_NAME
    echo "Compiling: $class"
  done
  echo "Finished compiling"
  echo "Adding appinfo Compatibility"
  echo 'if [ "$1" != "--getdata" ]' >> $APP_NAME
  echo 'then' >> $APP_NAME
  echo 'main $@' >> $APP_NAME
  echo 'fi' >> $APP_NAME
  chmod 777 $APP_NAME
  echo done
fi
