#!/bin/bash
VS_URL="https://git.vorax.org/Henry/VScript.git"
dl(){
rm -rf VScript
git clone $VS_URL 2>/dev/null &
pid=$! # Process Id of the previous running command
spin='-\|/'
i=0
while kill -0 $pid 2>/dev/null
do
  i=$(( (i+1) %4 ))
  dialog --backtitle "Vget" --title "Download Manager" --infobox "Downloading VScript\n${spin:$i:1}" 0 0
  sleep .1
done
}

getLibs(){
  for i in $(find src -maxdepth 1 -mindepth 1)
  do
    echo $(basename $i)
  done
}

selectLibs(){
  # echo $PWD
  # for i in $(getLibs)
  # do
  #   rm -rf $i/.en
  # done
  # rm -rf .menubuildfile
  # touch .menubuildfile
  # LIBSCOUNT=$(ls -1 ./src/ | wc -l)
  #
  # echo -n '--checklist "Select Libraries To Compile" 0 0 '$LIBSCOUNT >> .menubuildfile
  # array=($(getLibs))
  # echo $array
  # for (( i = 0; i < $LIBSCOUNT; i++ )); do
  #     printf " $(($i+1)) ${array[$i-1]}  off " >> .menubuildfile
  #     echo $(($i+1)) ${array[$i-1]}
  # done
  #
  # LIBS=$(dialog --file .menubuildfile 3>&1 1>&2 2>&3)
  # echo "libs"$LIBS
  # echo $array
  # for i in $LIBS
  # do
  #   touch "src/${array[$i-1]}"
  #   echo $i" i"
  # done

  # Clean up source folders
  rm -rf src/*/.en

  # Make the menu builder files
  rm -rf .menubuildfile && touch .menubuildfile

  # Get The Ammount Of libraries we have
  LIBSCOUNT=$(ls -1 ./src/ | wc -l)

  # Echo the begining of the command without a newline and esaping correctly
  echo -ne "--checklist \"Select Libraries To Compile\" 0 0 $LIBSCOUNT " >> .menubuildfile

  #Build a dialog
  LIBRARIES=$(ls src/)
  COUNT=1
  for lib in $LIBRARIES
  do
    echo -ne "$COUNT \"$lib\" off " >> .menubuildfile
    COUNT=$(($COUNT+1))
  done

  #Get output of dialog and
  OUTPUT=$(dialog --file .menubuildfile 3>&1 1>&2 2>&3)
  OUTARR=($OUTPUT)
  LIBARR=($LIBRARIES)
  for i in $OUTARR
  do
    echo -n "" > src/${LIBARR[$i-1]}/.en
  done
}

OUT=$(dialog --backtitle "Vget" \
--menu "Select VScript Components:" 0 0 4 \
1 "Get Latest VScript Release" \
2 "Don't Compile source" \
3 "Exit" \
3>&1 1>&2 2>&3)


case $OUT in
	"1")
		dl
		cd VScript
    selectLibs
    dialog --backtitle "Vget" --title "Build Info" --infobox "`./mkruntime buildlibs`" 0 0
    sleep 1s
		dialog --backtitle "Vget" --title "Build Info" --infobox "`./mkruntime build`" 0 0
    sleep 1s
		rm README.md help-template updatevramen vs-version-data
    sleep 1s
    dialog --backtitle "Vget" --title "Build Info" --infobox "Done" 0 0
    exit
		;;
	"2")
		dl
		dialog --backtitle "Vget" --title "Build Info" --infobox "Done`sleep 1s`" 0 0
    exit
		;;
	"3")
		exit
		;;
esac
