#!/bin/bash
VS_URL="https://git.vorax.org/Henry/VScript.git"
VER=1.0
dl(){
rm -rf VScript
git clone $VS_URL 2>/dev/null &
pid=$! # Process Id of the previous running command
spin='-\|/'
i=0
while kill -0 $pid 2>/dev/null
do
  i=$(( (i+1) %4 ))
  dialog --backtitle "Vget" --title "Download Manager" --infobox "Downloading VScript\n${spin:$i:1}" 0 0
  sleep .1
done
}

selectLibs(){
  for i in $(ls src)
  do
    rm -rf $i/.en
  done
  rm -rf .menubuildfile
  touch .menubuildfile
  LIBSCOUNT=$(ls -1 src | wc -l)

  echo -n '--reorder --buildlist "Select Libraries To Compile" 0 0 '$LIBSCOUNT >> .menubuildfile
  array=($(ls src))
  for (( i = 0; i < $LIBSCOUNT; i++ )); do
      printf " $(($i+1)) ${array[i-1]}  off " >> .menubuildfile
  done

  LIBS=$(dialog --file .menubuildfile 3>&1 1>&2 2>&3)

  for i in $LIBS
  do
    ./mkruntime enlib "${array[i]}"
  done
}

OUT=$(dialog --backtitle "Vget" \
--menu "Select VScript Components:" 0 0 4 \
1 "Get Latest VScript Release" \
2 "Don't Compile source" \
3 "Exit" \
3>&1 1>&2 2>&3)


case $OUT in
	"1")
		dl
		cd VScript
    selectLibs
    dialog --backtitle "Vget" --title "Build Info" --infobox "`./mkruntime buildlibs`" 0 0
    sleep 1s
		dialog --backtitle "Vget" --title "Build Info" --infobox "`./mkruntime build`" 0 0
    sleep 1s
		rm README.md help-template updatevramen vs-version-data
    sleep 1s
    dialog --backtitle "Vget" --title "Build Info" --infobox "Done" 0 0
    exit
		;;
	"2")
		dl
		dialog --backtitle "Vget" --title "Build Info" --infobox "Done`sleep 1s`" 0 0
    exit
		;;
	"3")
		exit
		;;
esac
