#!/bin/bash

#Application/Module configuration
APP_NAME=""
APP_VERSION=""
APP_TYPE=""
APP_FUZZY_NAME=""
#Past here... No touchey

appdata(){
  echo 'APP_NAME='"\"$APP_NAME\"" >> $1
  echo 'APP_FUZZY_NAME='"\"$APP_FUZZY_NAME\"" >> $1
  echo 'APP_VERSION='$APP_VERSION >> $1
  echo '' >> $1
  echo '#Pregenerated code ahead. Here be dragons?' >> $1
}

if [ "$APP_TYPE" == "mod" ]
then

  rm -f $APP_NAME.vmod
  touch $APP_NAME.vmod

  for class in $(ls src); do
    cat src/$class >> $APP_NAME.vmod
    echo "Added class $class to module"
  done
  echo 'loadedMods="$loadedMods\n'"$APP_NAME V$APP_VERSION: $APP_FUZZY_NAME" >> $APP_NAME.vmod
fi

if [ "$APP_TYPE" == "app" ]
then

  rm -f *.vs
  touch "$APP_NAME.vs"
  echo '#!/bin/bash' >> $APP_NAME.vs
  echo "Created empty app bundle"



  appdata "$APP_NAME.vs"
  echo "Added app data to bundle"

  if [ -e include/vsruntime.base ]
  then
    cat include/vsruntime.base >> $APP_NAME.vs
  fi


  if [ -d mods ]
  then
    for mod in $(ls mods)
    do
      cat mods/$mod >> $APP_NAME.vs
    done
  fi
  if [ ! -e src/main ]
  then
    echo "Main class not found, exiting"
    exit
  fi
  for class in $(ls src)
  do
    cat src/$class >> $APP_NAME.vs

  done

  echo 'main $@' >> $APP_NAME.vs

fi
