#!/bin/bash
source vs-version-data
info(){
echo -e "VScript runtime builder V0.5 for VScript $VS_VERSION $VS_CODENAME\n"
}

buildlibs(){
  cd libs
  for lib in $(ls ./)
  do
    cd $lib
    ./vramen
    cd ../
  done
  cd ..
}

build(){
  touch vsruntime.base
  echo "Created empty vsruntime.base"

  echo 'VS_VERSION='$VS_VERSION > vsruntime.base
  echo 'VS_CODENAME='"\"$VS_CODENAME\"" >> vsruntime.base
  echo '' >> vsruntime.base
  echo '#Pregenerated code ahead. Here be dragons?' >> vsruntime.base
  echo "Added built in variables"

  cat help-template >> vsruntime.base
  echo "Added help script"

  for lib in $(ls libs); do

    if [ -e "libs/$lib/.en" ]; then
      cat "libs/$lib/out.vlib" >> vsruntime.base
      echo -e "\n# end of library $lib \n" >> vsruntime.base
    fi

  done
}

clean(){
  rm vsruntime.base
  echo "Cleaned base"
}
$1
